sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
- 'pypy3'
install:
  - pip install pybuilder GitPython semver
  - pip install 'coverage~=4.4,<4.4.2'
  - pyb install_dependencies --verbose
script:
  - pyb --debug
deploy:
  - provider: pypi
    user: AlexeySanko
    server: https://upload.pypi.org/legacy/
    password:
      secure: ZBaWKmMPFunOezh9sLOrASavx9aal2pETwgfym5oRHUkGLqRZYF0HvT2pE38J5KNOReuC1CmP4mlmPqUNYsQ/taVFlFvi/VhO7HcRJI610QKcNl/bavjIPI7JHuydwtvNKUT/iCynKDmJs3Ir5DAcvOlaHVAX3E5HOHiwXpGbf/QFp4R5mR20x44fBjpdQbRc/osGc30sxEOaKoM7EqGEeMGCYgop7oUg7lltcWz9QfDm+OH4KAh87olWsPEpyRXUBQlSpceAUqnKSO3SeqtaKaNNpK0b76In/lPZGYcGNWUk+oz7kdm0NySupM7wlQGEdBnQeh4Igg02N+JGzd4NVerldbYjPXvHI8l066gagWPdaaqjarIXqeReyKMWdBFX7TTyK/3xTnhUBm9QwQzENY4gr+ICgbEmnJpzYCwjFUxodx9qfLRfHyyZ+j25dGOE7gTsFWqfWimCqGV3s51lIQP+Hly7M6+wXw07jderjEojtQmWQ84vkjzi4wBQLtpL5S0Fpt8suV//4qBIK+kFAkt8u2yQYdCq9j8SSe8FDenr+85F7hRMh4DjdU8bkQSxCRBaOAPFKBimwGJi2MXbtI1MS5vhi7lHFr8HkLX3SNsZDBtW2pBiw+CwiuSgmOzBI0ZKY9yF6MabRe46P6LOkRi3qJMQJ7Gsx3z9t4Uu/o=
    on:
      tags: true
      python: '2.7'
      repo: AlexeySanko/pybuilder_semver_git_tag
    distributions: bdist_wheel
  - provider: pypi
    user: AlexeySanko
    server: https://upload.pypi.org/legacy/
    password:
      secure: ZBaWKmMPFunOezh9sLOrASavx9aal2pETwgfym5oRHUkGLqRZYF0HvT2pE38J5KNOReuC1CmP4mlmPqUNYsQ/taVFlFvi/VhO7HcRJI610QKcNl/bavjIPI7JHuydwtvNKUT/iCynKDmJs3Ir5DAcvOlaHVAX3E5HOHiwXpGbf/QFp4R5mR20x44fBjpdQbRc/osGc30sxEOaKoM7EqGEeMGCYgop7oUg7lltcWz9QfDm+OH4KAh87olWsPEpyRXUBQlSpceAUqnKSO3SeqtaKaNNpK0b76In/lPZGYcGNWUk+oz7kdm0NySupM7wlQGEdBnQeh4Igg02N+JGzd4NVerldbYjPXvHI8l066gagWPdaaqjarIXqeReyKMWdBFX7TTyK/3xTnhUBm9QwQzENY4gr+ICgbEmnJpzYCwjFUxodx9qfLRfHyyZ+j25dGOE7gTsFWqfWimCqGV3s51lIQP+Hly7M6+wXw07jderjEojtQmWQ84vkjzi4wBQLtpL5S0Fpt8suV//4qBIK+kFAkt8u2yQYdCq9j8SSe8FDenr+85F7hRMh4DjdU8bkQSxCRBaOAPFKBimwGJi2MXbtI1MS5vhi7lHFr8HkLX3SNsZDBtW2pBiw+CwiuSgmOzBI0ZKY9yF6MabRe46P6LOkRi3qJMQJ7Gsx3z9t4Uu/o=
    on:
      tags: true
      python: '3.6'
      repo: AlexeySanko/pybuilder_semver_git_tag
    distributions: bdist_wheel